# Generated by Django 4.2.7 on 2024-10-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recyclable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='ca',
            new_name='CA',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='ct',
            new_name='CT',
        ),
        migrations.AddField(
            model_name='container',
            name='GU',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='container',
            name='HI',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='container',
            name='IA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='container',
            name='MA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='container',
            name='ME',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='container',
            name='MI',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='container',
            name='NY',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='container',
            name='OR',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='container',
            name='VT',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='container',
            name='alcohol_percentage',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AddField(
            model_name='container',
            name='alcoholic',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('yes', 'Yes'), ('no', 'No')], default='no', max_length=31),
        ),
        migrations.AddField(
            model_name='container',
            name='alcoholic_drinks_type',
            field=models.CharField(choices=[('NA', 'NA'), ('unknown', 'Unknown'), ('absinthe', 'Absinthe'), ('baijiu', 'Baijiu'), ('beer', 'Beer'), ('bourbon', 'Bourbon'), ('brandy', 'Brandy'), ('cocktail_mix', 'Cocktail Mix'), ('cognac', 'Cognac'), ('gin', 'Gin'), ('hard_seltzer', 'Hard Seltzer'), ('makgeolli', 'Makgeolli'), ('malt', 'Malt'), ('rum', 'Rum'), ('sake', 'Sake'), ('scotch', 'Scotch'), ('soju', 'Soju'), ('tequila', 'Tequila'), ('vermouth', 'Vermouth'), ('vodka', 'Vodka'), ('whisky', 'Whisky'), ('wine', 'Wine'), ('other', 'Other')], default='NA', max_length=31),
        ),
        migrations.AddField(
            model_name='container',
            name='beverage_type',
            field=models.CharField(choices=[('NA', 'NA'), ('unknown', 'Unknown'), ('water', 'Water'), ('flavored_water', 'Flavored Water'), ('coconut_water', 'Coconut Water'), ('soft_drink', 'Soft Drink'), ('soft_drink_alternative', 'Soft Drink Alternative'), ('sports_drink', 'Sports Drink'), ('energy_drink', 'Energy Drink'), ('alcoholic_beverage', 'Alcoholic Beverage'), ('dairy', 'Dairy'), ('substitute_milk', 'Substitute Milk'), ('protein_shake', 'Protein Shake'), ('fruit_juice', 'Fruit Juice'), ('vegetable_juice', 'Vegetable Juice'), ('coffee', 'Coffee'), ('tea', 'Tea'), ('probiotics', 'Probiotics'), ('rest', 'Rest')], default='unknown', max_length=31),
        ),
        migrations.AddField(
            model_name='container',
            name='content_type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('beverage', 'Beverage'), ('candy', 'Candy'), ('oil', 'Oil'), ('cosmetics', 'Cosmetics'), ('pharmaceutical', 'Pharmaceutical'), ('food', 'Food'), ('condiments', 'Condiments'), ('flammable', 'Flammable'), ('rest', 'Rest')], default='unknown', max_length=31),
        ),
        migrations.AddField(
            model_name='container',
            name='hazardous',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('yes', 'Yes'), ('no', 'No')], default='unknown', max_length=31),
        ),
        migrations.AddField(
            model_name='container',
            name='juice_percentage',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AddField(
            model_name='container',
            name='made_in',
            field=models.CharField(choices=[('UNK', 'Unknown'), ('USA', 'USA'), ('CAN', 'Canada'), ('GBR', 'United Kingdom')], default='UNK', max_length=31),
        ),
        migrations.AddField(
            model_name='container',
            name='ribbed',
            field=models.CharField(choices=[('ribbed_body', 'Ribbed Body'), ('ribbed_neck', 'Ribbed Neck'), ('NA', 'NA'), ('unknown', 'Unknown')], default='NA', max_length=31),
        ),
        migrations.AddField(
            model_name='container',
            name='rigidity',
            field=models.CharField(choices=[('rigid', 'Rigid'), ('flexible', 'Flexible'), ('unknown', 'Unknown')], default='unknown', max_length=31),
        ),
        migrations.AddField(
            model_name='container',
            name='ringed',
            field=models.CharField(choices=[('single_ring', 'Single Ring'), ('double_ring', 'Double Ring'), ('NA', 'NA'), ('unknown', 'Unknown')], default='NA', max_length=31),
        ),
        migrations.AddField(
            model_name='container',
            name='shape',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('bottle', 'Bottle'), ('can_beverage', 'Can Beverage'), ('can_food', 'Can Food'), ('cup', 'Cup'), ('jar', 'Jar'), ('cubic', 'Cubic'), ('egg_shaped', 'Egg Shaped'), ('bag_wrapper', 'Bag Wrapper'), ('pouch', 'Pouch'), ('rest', 'Rest')], default='unknown', max_length=31),
        ),
        migrations.AddField(
            model_name='container',
            name='visual_volume',
            field=models.CharField(choices=[('NA', 'NA'), ('small', 'Small'), ('LT_24_OZ', 'Less than 24 oz'), ('GT_24_OZ', 'Greater than 24 oz')], default='NA', max_length=31),
        ),
        migrations.AddField(
            model_name='container',
            name='wine_bottle_shape',
            field=models.CharField(choices=[('NA', 'NA'), ('unknown', 'Unknown'), ('alsace', 'Alsace'), ('bordeaux', 'Bordeaux'), ('burgundy', 'Burgundy'), ('champagne', 'Champagne'), ('chianti', 'Chianti'), ('port', 'Port'), ('provence', 'Provence'), ('other', 'Other')], default='NA', max_length=31),
        ),
        migrations.AddField(
            model_name='container',
            name='wine_type',
            field=models.CharField(choices=[('NA', 'NA'), ('unknown', 'Unknown'), ('albariño', 'Albariño'), ('cabernet_franc', 'Cabernet Franc'), ('cabernet_sauvignon', 'Cabernet Sauvignon'), ('cava', 'Cava'), ('champagne', 'Champagne'), ('chardonnay', 'Chardonnay'), ('chenin_blanc', 'Chenin Blanc'), ('gewürztraminer', 'Gewürztraminer'), ('grüner_veltliner', 'Grüner Veltliner'), ('madeira', 'Madeira'), ('malbec', 'Malbec'), ('merlot', 'Merlot'), ('muscat', 'Muscat'), ('pinot_blanc', 'Pinot Blanc'), ('pinot_gris', 'Pinot Gris'), ('pinot_noir', 'Pinot Noir'), ('port', 'Port'), ('prosecco', 'Prosecco'), ('red_blend', 'Red Blend'), ('riesling', 'Riesling'), ('rosé', 'Rosé'), ('sancerre', 'Sancerre'), ('sangiovese', 'Sangiovese'), ('sauvignon_blanc', 'Sauvignon Blanc'), ('sherry', 'Sherry'), ('shiraz', 'Shiraz'), ('sparkling_wine', 'Sparkling Wine'), ('sylvaner', 'Sylvaner'), ('white_blend', 'White Blend'), ('zinfandel', 'Zinfandel')], default='NA', max_length=31),
        ),
    ]
