# Generated by Django 4.2.7 on 2024-10-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recyclable', '0002_rename_ca_container_ca_rename_ct_container_ct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='aws_entity_tag',
            new_name='AWS_entity_tag',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='aws_region_name',
            new_name='AWS_region_name',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='s3_bucket_name',
            new_name='S3_bucket_name',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='s3_object_key',
            new_name='S3_object_key',
        ),
        migrations.AddField(
            model_name='image',
            name='company_name',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='image',
            name='container_in_frame',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AddField(
            model_name='image',
            name='count',
            field=models.CharField(choices=[('empty', 'Empty'), ('solo', 'Solo'), ('multiple', 'Multiple')], default='solo', max_length=31),
        ),
        migrations.AddField(
            model_name='image',
            name='cube_sn',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='image',
            name='database_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='image',
            name='deposit_ID',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='image',
            name='hands_in_image',
            field=models.CharField(choices=[('no_hands', 'No Hands'), ('hands', 'Hands'), ('blurry_hands_in', 'Blurry Hands In'), ('blurry_hands_out', 'Blurry Hands Out')], default='no_hands', max_length=31),
        ),
        migrations.AddField(
            model_name='image',
            name='image_ID',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='image',
            name='image_height',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AddField(
            model_name='image',
            name='image_quality',
            field=models.CharField(choices=[('valid_image', 'Valid Image'), ('invalid_image', 'Invalid Image'), ('unknown_image', 'Unknown Image'), ('partially_shown', 'Partially Shown'), ('blurry_moving_belt', 'Blurry Moving Belt'), ('out_of_focus', 'Out of Focus'), ('bad_lighting', 'Bad Lighting'), ('blurry_moving_container', 'Blurry Moving Container')], default='unknown_image', max_length=31),
        ),
        migrations.AddField(
            model_name='image',
            name='image_width',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AddField(
            model_name='image',
            name='imager_version',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='image',
            name='label',
            field=models.CharField(choices=[('neck_only', 'Neck Only'), ('body_only', 'Body Only'), ('neither', 'Neither'), ('neck_and_body', 'Neck and Body')], default='body_only', max_length=31),
        ),
        migrations.AddField(
            model_name='image',
            name='lid_cap',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('true', 'True'), ('false', 'False')], default='unknown', max_length=31),
        ),
        migrations.AddField(
            model_name='image',
            name='orientation_style',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('standing_up', 'Standing Up'), ('leaning', 'Leaning'), ('orthogonal', 'Orthogonal'), ('parallel', 'Parallel')], default='unknown', max_length=31),
        ),
        migrations.AddField(
            model_name='image',
            name='store_name',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='image',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
