# Generated by Django 4.2.7 on 2024-10-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recyclable', '0003_rename_aws_entity_tag_image_aws_entity_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='OR',
            new_name='Or',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='CA',
            new_name='ca',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='CT',
            new_name='ct',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='GU',
            new_name='gu',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='HI',
            new_name='hi',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='IA',
            new_name='ia',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='MA',
            new_name='ma',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='ME',
            new_name='me',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='MI',
            new_name='mi',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='NY',
            new_name='ny',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='VT',
            new_name='vt',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='AWS_entity_tag',
            new_name='aws_entity_tag',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='AWS_region_name',
            new_name='aws_region_name',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='deposit_ID',
            new_name='deposit_id',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_ID',
            new_name='image_id',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='S3_bucket_name',
            new_name='s3_bucket_name',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='S3_object_key',
            new_name='s3_object_key',
        ),
    ]
