# Generated by Django 4.2.7 on 2024-10-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recyclable', '0004_rename_or_container_or_rename_ca_container_ca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='material_color',
            field=models.CharField(choices=[('amber', 'Amber'), ('beige', 'Beige'), ('black', 'Black'), ('blue', 'Blue'), ('brown', 'Brown'), ('cobalt_blue', 'Cobalt Blue'), ('emerald_green', 'Emerald Green'), ('fluorescent_green', 'Fluorescent Green'), ('frosted', 'Frosted'), ('gold', 'Gold'), ('green', 'Green'), ('grey', 'Grey'), ('holographic', 'Holographic'), ('khaki', 'Khaki'), ('multi_color', 'Multi Color'), ('navy_blue', 'Navy Blue'), ('olive_green', 'Olive Green'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('red', 'Red'), ('silver', 'Silver'), ('translucent', 'Translucent'), ('transparent', 'Transparent'), ('unknown', 'Unknown'), ('white', 'White'), ('yellow', 'Yellow')], default='unknown', max_length=31),
        ),
    ]
